apiVersion: v1
kind: Service
metadata:
  labels:
    app: consulta
  name: consulta
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: consulta
  sessionAffinity: None
  type: LoadBalancer